Модуль 12. Многопоточность. Конкурентный код.
Dima1231231231412/Fintex pull request #9
Opened 2023-11-18 10:30 UTC by Dima1231231231412

2023-11-19 21:20 UTC, GordPavel requested changes

2023-11-19 21:20 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/controllers/CurrentWeatherCacheController.java
> +    public Weather getAndAddCurrentWeatherInCity(@PathVariable String city) throws SQLException {
не нужно реализовывать отдельный контроллер. Тебе нужно поменять только сервис или DAO классы

2023-11-19 21:20 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/service/WeatherCache.java
> +public class WeatherCache {
ты реализуешь просто абстрактный кэш, нет необходимости его специализировать под `Weather`. Сделай generic

2023-11-19 21:20 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/service/WeatherCache.java
> +    private final long fifteenMinutesInMillis = 900000;
почему этот параметр нельзя настраивать? передавай через конструктор

2023-11-19 21:20 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/service/WeatherCache.java
> +    WeatherApiClientService weatherApiClientService;
не нужно передавать сюда эти Бины, кэш не зависит от провайдеров. Достаточно сделать метод 
```java
interface Cache{
   public <T> T get(Object key, Supplier<T> supplier);
}
```

2023-11-19 21:20 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/controllers/CurrentWeatherCacheController.java
> +        return weatherCache.getWeather(city, webClient);
по сути бин все ещё передается через параметр
https://github.com/Dima1231231231412/Fintex/pull/4#discussion_r1359327912

2023-11-19 21:20 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/service/WeatherCache.java
> +    private final WeakHashMap<String, Weather> lrucache = new WeakHashMap<>(maxSize, 0.75f);
LRU кэш работает не так – мапа не хранит сами значения, а только ссылки на узлы в списке, в котором уже хранятся значения

2023-11-19 21:20 UTC, GordPavel commented on fintex/src/test/java/com/example/springapp/WeatherCacheTests.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
не нужно делать `SpringBootTest` для проверки кэша – достаточно просто юнита

2023-11-20 11:00 UTC, Dima1231231231412 commented on fintex/src/main/java/com/example/springapp/service/WeatherCache.java
> +public class WeatherCache {
Так составлено задание)

2023-11-20 11:02 UTC, Dima1231231231412 commented on fintex/src/main/java/com/example/springapp/service/WeatherCache.java
> +public class WeatherCache {
Как он может быть абстрактным, если в этом кэше напрямую обращение к БД и таблице Weather?

2023-11-20 11:04 UTC, Dima1231231231412 commented on fintex/src/main/java/com/example/springapp/service/WeatherCache.java
> +    private final long fifteenMinutesInMillis = 900000;
Про параметр fifteenMinutesInMillis идёт речь?

2023-11-20 19:27 UTC, Dima1231231231412 commented
Такая реализация кэша возможна, если не использовать это  https://github.com/Dima1231231231412/Fintex/pull/9#discussion_r1398495310 ?

2023-11-21 09:08 UTC, GordPavel requested changes

2023-11-21 09:08 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/cache/WeatherCache.java
> +public class WeatherCache<T> implements Cache {
почему это все ещё `WeatherCache`? Тут ни что не ограничивает именно Weather типом

2023-11-21 09:08 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/cache/Cache.java
> +public interface Cache {
не вижу get операции

2023-11-21 09:08 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/cache/WeatherCache.java
> +    public final WeakHashMap<Object, LruListNode<T>> lrucache = new WeakHashMap<>(maxSize, 0.75f);
прочитай ещё раз алгоритм LRU кэша. Тебе не нужен accessCount. У тебя только 
```java
  private Map<Object, Node<Object>> keysMap;
  private Node linkedList;
  private static class Node<T>{
     private T value;
     private Node nextNode;
     private Node previousNode;
  }
```
![lru_cache](https://github.com/Dima1231231231412/Fintex/assets/25331582/e7c17f3b-c24a-46ed-907a-e4481a2682c4)

2023-11-21 09:08 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/service/WeatherApiClientService.java
> +        WeatherCache<Weather> weatherCache = new WeatherCache<>();
ты на каждый запрос собираешь новый объект кэша, который очистится сборщиком мусора после завершения запроса. Как кэш это не будет работать

2023-11-21 09:08 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/cache/WeatherCache.java
> +public class WeatherCache<T> implements Cache {
не потокобезопасный

2023-11-27 07:45 UTC, GordPavel requested changes
1. Кэш не выполняет свою непосредственную задачу – твои же слова 
> В моём понимании для уменьшения времени запроса и снижения загруженности сетевого трафика
ВСЕГДА выполняется запрос в сторонний сервис, потом уже работа с кэшем. А должно быть так, что сначала проверяем в кэше, если данных нет, то уже идем в сторонний сервис. Если данные есть, ТО ЗАПРОСА В СТОРОННИЙ СЕРВИС НЕ ДОЛЖНО БЫТЬ.
2. В задании было сказано про потокобезопасность. Это требование не выполнено совсем

2023-11-27 07:45 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/service/WeatherApiClientService.java
> +                weatherCache.keysMap.remove(location);
нельзя обращаться к полям другого объекта напрямую

2023-11-27 07:45 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/service/WeatherApiClientService.java
> +                return weatherCache.get(location,()-> weather);
смысла от такого кэша все равно нет. У тебя сначала ВСЕГДА запрашиваются данные из стороннего клиента, потом проверяется, есть ли в кэше или нет

2023-11-27 07:45 UTC, GordPavel commented on fintex/src/main/java/com/example/springapp/cache/Cache.java
> +public class Cache<T> implements CacheDao<T> {
по заданию кэш должен быть потокобезопасный

2023-11-29 15:46 UTC, GordPavel approved these changes
с очень большой натяжкой могу поставить аппрув

2023-11-29 16:05 UTC, merged